Workflow Fix.

diff --git a/.github/workflows/push-aab-to-google-play-store.yml b/.github/workflows/push-aab-to-google-play-store.yml
--- a/.github/workflows/push-aab-to-google-play-store.yml
+++ b/.github/workflows/push-aab-to-google-play-store.yml
@@ -15,6 +15,18 @@ on:
         description: App ID.
         required: true
         type: string
+      track:
+        description: Track.
+        required: true
+        type: string
+      merged-native-libs-symbols-artifact-name:
+        description: Merged Native Libs Symbols Artifact Name
+        required: false
+        type: string
+      merged-native-libs-symbols-file-name:
+        description: Merged Native Libs Symbols File Name
+        required: false
+        type: string
   workflow_call:
     inputs:
       aab-file-name:
@@ -29,6 +41,18 @@ on:
         description: App ID.
         required: true
         type: string
+      track:
+        description: Track.
+        required: true
+        type: string
+      merged-native-libs-symbols-artifact-name:
+        description: Merged Native Libs Symbols Artifact Name
+        required: false
+        type: string
+      merged-native-libs-symbols-file-name:
+        description: Merged Native Libs Symbols File Name
+        required: false
+        type: string
     secrets:
       GITHUB_ENV_TOKEN:
         description: GITHUB_ENV_TOKEN
@@ -41,10 +65,17 @@ jobs:
   download-latest-release-and-push-to-google-play:
     runs-on: ubuntu-latest
     steps:
-      - name: Validate Inputs
+      - name: Validate AAB Inputs
         run: |
           if [ -z "${{ inputs.aab-file-name }}" ] && [ -z "${{ inputs.aab-artifact-name }}" ]; then
             echo "Either aab-file-name or aab-artifact-name is required"
+            exit 1
+          fi
+
+      - name: Validate Merged Native Libs Inputs
+        run: |
+          if [ -z "${{ inputs.merged-native-libs-symbols-file-name }}" ] && [ -z "${{ inputs.merged-native-libs-symbols-artifact-name }}" ]; then
+            echo "Either merged-native-libs-symbols-file-name or merged-native-libs-symbols-artifact-name is required"
             exit 1
           fi
 
@@ -59,11 +90,27 @@ jobs:
           token: ${{ secrets.GITHUB_ENV_TOKEN }}
 
       - if: ${{ inputs.aab-artifact-name == '' && inputs.aab-file-name != '' }}
-        name: release-downloader
+        name: Download AAB File from Latest Release
         uses: robinraju/release-downloader@v1.8
         with:
           tag: ${{ steps.get-latest-release.outputs.release }}
           fileName: '${{ inputs.aab-file-name }}-${{ steps.get-latest-release.outputs.release }}.aab'
+          out-file-path: release
+
+      - if: ${{ inputs.aab-artifact-name == '' && inputs.aab-file-name != '' }}
+        name: Download Mapping File from Latest Release
+        uses: robinraju/release-downloader@v1.8
+        with:
+          tag: ${{ steps.get-latest-release.outputs.release }}
+          fileName: mapping.txt
+          out-file-path: release
+
+      - if: ${{ inputs.merged-native-libs-symbols-artifact-name == '' && inputs.merged-native-libs-symbols-file-name != '' }}
+        name: Download Merged Native Libs from Latest Release
+        uses: robinraju/release-downloader@v1.8
+        with:
+          tag: ${{ steps.get-latest-release.outputs.release }}
+          fileName: ${{ inputs.merged-native-libs-symbols-file-name }}
           out-file-path: release
 
       - if: ${{ inputs.aab-artifact-name != '' && inputs.aab-file-name == '' }}
@@ -71,15 +118,40 @@ jobs:
         with:
           name: ${{ inputs.aab-artifact-name }}
 
+      - if: ${{ inputs.aab-artifact-name != '' && inputs.aab-file-name == '' }}
+        uses: actions/download-artifact@v3
+        with:
+          name: mapping
+
+      - if: ${{ inputs.merged-native-libs-symbols-artifact-name != '' && inputs.merged-native-libs-symbols-file-name == '' }}
+        uses: actions/download-artifact@v3
+        with:
+          name: ${{ inputs.merged-native-libs-symbols-artifact-name }}
+
       - if: ${{ inputs.aab-artifact-name == '' && inputs.aab-file-name != '' }}
-        name: Normalize AAB File Name
+        name: Normalize Release File Names
         run: |
           mv ./release/${{ inputs.aab-file-name }}-${{ steps.get-latest-release.outputs.release }}.aab ./app-release.aab
+          mv ./release/mapping.txt mapping.txt
+
+      - if: ${{ inputs.merged-native-libs-symbols-artifact-name == '' && inputs.merged-native-libs-symbols-file-name != '' }}
+        name: Normalize Release File Names
+        run: |
+          mv ./release/${{ inputs.merged-native-libs-symbols-file-name }}.zip ./symbols.zip
 
       - if: ${{ inputs.aab-artifact-name != '' && inputs.aab-file-name == '' }}
-        name: Normalize AAB File Name
+        name: Normalize Artifact File Names
         run: |
           mv ./${{ inputs.aab-artifact-name }}/app-release.aab ./app-release.aab
+          mv ./${{ inputs.aab-artifact-name }}/mapping.txt mapping.txt
+
+      - if: ${{ inputs.merged-native-libs-symbols-artifact-name != '' && inputs.merged-native-libs-symbols-file-name == '' }}
+        name: Normalize Artifact File Names
+        run: |
+          mv ./${{ inputs.merged-native-libs-symbols-artifact-name }}/symbols.zip ./symbols.zip
+
+      - name: Extract Flutter Debug Symbols
+        run: unzip -q ./symbols.zip -d symbols
 
       - name: 'Check Release Notes Existence'
         id: release_notes_exists
@@ -102,5 +174,5 @@ jobs:
           inAppUpdatePriority: 2
           userFraction: 1
           whatsNewDirectory: whatsnew
-          mappingFile: app/build/outputs/mapping/release/mapping.txt
-          debugSymbols: app/intermediates/merged_native_libs/release/out/lib
+          mappingFile: mapping.txt
+          debugSymbols: symbols
